In [12]:
import numpy as np
#Q1: Questions on Basic NumPy Array 
#(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
arr = np.array([1,2,3,6,4,5])
print(arr)
reverse_arr = arr[::-1]
print(reverse_arr)

[1 2 3 6 4 5]
[5 4 6 3 2 1]


In [14]:
#(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods  
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
print(array1.flatten())

[1 2 3 2 4 5 1 2 3]


In [16]:
#(c) Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]]) ,arr2 = np.array([[1, 2], [3, 4]]) 
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print(arr1 == arr2)

[[ True  True]
 [ True  True]]


In [18]:
#(d) Find the most frequent value and their indice(s) in the following arrays: i. x = np.array([1,2,3,4,5,1,2,1,1,1]),ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
x = np.array([1,2,3,4,5,1,2,1,1,1])
np.unique(x,return_inverse=True,return_index=True,return_counts=True)

(array([1, 2, 3, 4, 5]),
 array([0, 1, 2, 3, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 0, 0, 0], dtype=int64),
 array([5, 2, 1, 1, 1], dtype=int64))

In [20]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
np.unique(y,return_inverse=True,return_index=True,return_counts=True)

(array([1, 2, 3, 4]),
 array([0, 3, 4, 5], dtype=int64),
 array([0, 0, 0, 1, 2, 3, 1, 3, 2, 2], dtype=int64),
 array([3, 2, 3, 2], dtype=int64))

In [26]:
 #For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find 
#i.Sum of all elements 
#ii.Sum of all elements row-wise  
#iii.Sum of all elements column-wise 
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(gfg.sum())
print(gfg.sum(axis=1))
print(gfg.sum(axis=0))

45
[[14]
 [16]
 [15]]
[[20  9 16]]


In [36]:
#(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find 
#i.Sum of diagonal elements 
#ii.Eigen values of matrix  
#iii.Eigen vectors of matrix  
#iv.Inverse of matrix  
#v.Determinant of matrix  
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print(np.trace(n_array))
print(np.linalg.eig(n_array))
print(np.linalg.inv(n_array))
print(np.linalg.det(n_array))

176
EigResult(eigenvalues=array([98.16835147, 28.097044  , 49.73460452]), eigenvectors=array([[ 0.4574917 ,  0.34637121, -0.15017693],
       [ 0.28447814, -0.72784061, -0.4852124 ],
       [ 0.84248058,  0.59184038,  0.8614034 ]]))
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [48]:
#(g) Multiply the following matrices and also find covariance between matrices using NumPy: 
#i. p = [[1, 2], [2, 3]] 
   #q = [[4, 5], [6, 7]] 
#ii.p = [[1, 2], [2, 3], [4, 5]] 
   #q = [[4, 5, 1], [6, 7, 2]] 
p1 = np.array([[1,2],[2,3]])
q1 = np.array([[4,5],[6,7]])
print(np.dot(p1,q1))
print(np.cov(p1.flatten(),q1.flatten()))

p2 = np.array([[1, 2], [2, 3], [4, 5]] )
q2 = np.array([[4, 5, 1], [6, 7, 2]])
print(np.dot(p2,q2))
print(np.cov(p2.flatten(),q2.flatten()))

[[16 19]
 [26 31]]
[[0.66666667 1.        ]
 [1.         1.66666667]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [11]:
import numpy as np
#(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),find inner, outer and cartesian product? 
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])
print(np.inner(x,y))
print(np.outer(x.flatten(),y.flatten()))
from itertools import product
cartesian = np.array(list(product(x.flatten(), y.flatten())))
print(cartesian)

[[17 52]
 [13 62]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [13]:
#(a)For the array: array = np.array([[1, -2, 3],[-4, 5, -6]]) 
array = np.array([[1, -2, 3],[-4, 5, -6]])
#i. Find element-wise absolute value 
print(np.abs(array))
#ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.
flat = array.flatten()
print(np.percentile(flat, [25, 50, 75]))
print(np.percentile(array, [25, 50, 75], axis=0))
print(np.percentile(array, [25, 50, 75], axis=1))
#iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row
print(np.mean(flat), np.median(flat), np.std(flat))
print(np.mean(array, axis=0))
print(np.median(array, axis=0))
print(np.std(array, axis=0))

print(np.mean(array, axis=1))
print(np.median(array, axis=1))
print(np.std(array, axis=1))



[[1 2 3]
 [4 5 6]]
[-3.5 -0.5  2.5]
[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
-0.5 -0.5 3.8622100754188224
[-1.5  1.5 -1.5]
[-1.5  1.5 -1.5]
[2.5 3.5 4.5]
[ 0.66666667 -1.66666667]
[ 1. -4.]
[2.05480467 4.78423336]


In [17]:
#For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling and truncated value, rounded values 
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a))


[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


In [27]:
#a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find  
#Sorted array,Indices of sorted array,4 smallest elements,5 largest elements 

array = np.array([10, 52, 62, 16, 16, 54, 453])
print(np.sort(array))

print(np.argsort(array))
print(np.sort(array)[:4])
print(np.sort(array)[-5:])


[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  52  54  62 453]


In [6]:
import numpy as np
#(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find 
#i.Integer elements only 
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
print(array[array == np.floor(array)])
#ii.Float elements only 
print(array[array != np.floor(array)])


[1. 2. 3. 2.]
[1.2 2.2]
